adminprefix: "&8[GM]"
range.default: 40
range.dm: 40
range.closedm: 10
range.fardm: 110
range.me: 110
range.strongshout: 160
range.shout: 110
range.weakshout: 80
range.strongwhisper: 16
range.whisper: 3
range.weakwhisper: 1
