adminprefix: "&8[GM]"
range.default: 18
range.dm: 18
range.closedm: 5
range.fardm: 80
range.me: 18
range.strongshout: 80
range.shout: 60
range.weakshout: 36
range.strongwhisper: 9
range.whisper: 3
range.weakwhisper: 1

