name: KMChat
main: KMChat.KMChat
version: 0.7
commands:
   me:
      description: Nothing
      usage: /<command>
      permission-message: You don't have <permission>
   tell:
      description: Nothing
      usage: /<command>
      permission-message: You don't have <permission>
   msg:
      description: Nothing
      usage: /<command>
      permission-message: You don't have <permission>
   ingamerestart:
      description: Nothing
      usage: /<command>
      permission-message: You don't have <permission>
   alwaysgm:      
      description: Nothing
      usage: /<command>
      permission-message: You don't have <permission>
permissions:
    KMChat.tell:
        description: Allow to tell
        default: op
    KMChat.gm:
        description: GameMaster
        default: op
